module_name: Lunar
compatible_versions: 1.0.0+
author: derikon
category: payment
tags:
  - lunar
  - lunar.app
  - Lunar payment provider
  - Accept online payments
  - Online payments
  - Easy implementation
  - Easy setup
  - Lunar for merchants
  - Visa
  - Mastercard
  - Google Pay
  - Apple Pay
  - Lunar plugin
  - Plugin

description_short: Install the Lunar plugin for Thirtybees and start accepting online payments on your website in just a matter of minutes! Free multi-language support.
description: description.md
images:
  - image-1.png
  - image-2.png
  - image-3.png
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4